version: "3"
services:
  hub:
    image: selenium/hub:4.16.1-20231219
  chrome:
    image: selenium/node-chrome:4.16.1-20231219
    shm_size: '2g'
    depends_on:
    - hub
    deploy:
     replicas: 0
    env_file: .env
  
  
  